# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{surveyor}
  s.version = "0.11.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brian Chamberlain", "Mark Yoon"]
  s.date = %q{2010-08-23}
  s.email = %q{yoon@northwestern.edu}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/controllers/surveyor_controller.rb",
     "app/helpers/survey_form_builder.rb",
     "app/helpers/surveyor_helper.rb",
     "app/models/answer.rb",
     "app/models/dependency.rb",
     "app/models/dependency_condition.rb",
     "app/models/question.rb",
     "app/models/question_group.rb",
     "app/models/response.rb",
     "app/models/response_set.rb",
     "app/models/survey.rb",
     "app/models/survey_section.rb",
     "app/models/validation.rb",
     "app/models/validation_condition.rb",
     "app/views/layouts/surveyor_default.html.erb",
     "app/views/partials/_answer.html.haml",
     "app/views/partials/_question.html.haml",
     "app/views/partials/_question_group.html.haml",
     "app/views/surveyor/edit.html.haml",
     "app/views/surveyor/new.html.haml",
     "app/views/surveyor/show.html.haml",
     "config/routes.rb",
     "features/step_definitions/surveyor_steps.rb",
     "features/step_definitions/web_steps.rb",
     "features/support/env.rb",
     "features/support/paths.rb",
     "features/surveyor.feature",
     "init.rb",
     "install.rb",
     "lib/fixtures_extensions.rb",
     "lib/generators/surveyor/custom_generator.rb",
     "lib/generators/surveyor/install_generator.rb",
     "lib/generators/surveyor/templates/app/controllers/surveyor_controller.rb",
     "lib/generators/surveyor/templates/app/helpers/surveyor_helper.rb",
     "lib/generators/surveyor/templates/app/views/layouts/surveyor_custom.html.erb",
     "lib/generators/surveyor/templates/db/migrate/add_correct_answer_id_to_questions.rb",
     "lib/generators/surveyor/templates/db/migrate/add_display_order_to_surveys.rb",
     "lib/generators/surveyor/templates/db/migrate/add_index_to_response_sets.rb",
     "lib/generators/surveyor/templates/db/migrate/add_index_to_surveys.rb",
     "lib/generators/surveyor/templates/db/migrate/add_unique_indicies.rb",
     "lib/generators/surveyor/templates/db/migrate/create_answers.rb",
     "lib/generators/surveyor/templates/db/migrate/create_dependencies.rb",
     "lib/generators/surveyor/templates/db/migrate/create_dependency_conditions.rb",
     "lib/generators/surveyor/templates/db/migrate/create_question_groups.rb",
     "lib/generators/surveyor/templates/db/migrate/create_questions.rb",
     "lib/generators/surveyor/templates/db/migrate/create_response_sets.rb",
     "lib/generators/surveyor/templates/db/migrate/create_responses.rb",
     "lib/generators/surveyor/templates/db/migrate/create_survey_sections.rb",
     "lib/generators/surveyor/templates/db/migrate/create_surveys.rb",
     "lib/generators/surveyor/templates/db/migrate/create_validation_conditions.rb",
     "lib/generators/surveyor/templates/db/migrate/create_validations.rb",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_arrows_leftright.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_arrows_updown.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_close.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_doc.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_folder_closed.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_folder_open.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_minus.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_plus.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_11x11_icon_resize_se.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_35x9_colorpicker_indicator.gif.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_7x7_arrow_down.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_7x7_arrow_left.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_7x7_arrow_right.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/222222_7x7_arrow_up.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_11x11_icon_arrows_leftright.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_11x11_icon_arrows_updown.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_11x11_icon_close.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_11x11_icon_doc.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_11x11_icon_folder_closed.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_11x11_icon_folder_open.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_11x11_icon_minus.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_11x11_icon_plus.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_7x7_arrow_down.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_7x7_arrow_left.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_7x7_arrow_right.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/454545_7x7_arrow_up.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_11x11_icon_arrows_leftright.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_11x11_icon_arrows_updown.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_11x11_icon_close.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_11x11_icon_doc.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_11x11_icon_folder_closed.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_11x11_icon_folder_open.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_11x11_icon_minus.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_11x11_icon_plus.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_7x7_arrow_down.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_7x7_arrow_left.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_7x7_arrow_right.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/888888_7x7_arrow_up.gif",
     "lib/generators/surveyor/templates/public/images/surveyor/dadada_40x100_textures_02_glass_75.png",
     "lib/generators/surveyor/templates/public/images/surveyor/e6e6e6_40x100_textures_02_glass_75.png",
     "lib/generators/surveyor/templates/public/images/surveyor/ffffff_40x100_textures_01_flat_0.png",
     "lib/generators/surveyor/templates/public/images/surveyor/ffffff_40x100_textures_02_glass_65.png",
     "lib/generators/surveyor/templates/public/javascripts/surveyor/accessibleUISlider.jQuery.js",
     "lib/generators/surveyor/templates/public/javascripts/surveyor/jquery-1.2.6.js",
     "lib/generators/surveyor/templates/public/javascripts/surveyor/jquery-ui-personalized-1.5.3.js",
     "lib/generators/surveyor/templates/public/javascripts/surveyor/jquery.form.js",
     "lib/generators/surveyor/templates/public/javascripts/surveyor/surveyor.js",
     "lib/generators/surveyor/templates/public/stylesheets/surveyor/jquery-ui-slider-additions.css",
     "lib/generators/surveyor/templates/public/stylesheets/surveyor/reset.css",
     "lib/generators/surveyor/templates/public/stylesheets/surveyor/sass/surveyor.sass",
     "lib/generators/surveyor/templates/public/stylesheets/surveyor/surveyor.css",
     "lib/generators/surveyor/templates/public/stylesheets/surveyor/ui.theme.css",
     "lib/generators/surveyor/templates/surveys/README_FOR_CUSTOM_SURVEYOR.md",
     "lib/generators/surveyor/templates/surveys/kitchen_sink_survey.rb",
     "lib/surveyor.rb",
     "lib/surveyor/acts_as_response.rb",
     "lib/surveyor/common.rb",
     "lib/surveyor/engine.rb",
     "lib/surveyor/survey_methods.rb",
     "lib/surveyor/surveyor_controller_methods.rb",
     "lib/tasks/surveyor_tasks.rake",
     "lib/xml_formatter.rb",
     "script/surveyor/answer.rb",
     "script/surveyor/base.rb",
     "script/surveyor/dependency.rb",
     "script/surveyor/dependency_condition.rb",
     "script/surveyor/parser.rb",
     "script/surveyor/question.rb",
     "script/surveyor/question_group.rb",
     "script/surveyor/specs/answer_spec.rb",
     "script/surveyor/specs/question_spec.rb",
     "script/surveyor/specs/spec_helper.rb",
     "script/surveyor/specs/survey_section_spec.rb",
     "script/surveyor/specs/validation_condition_spec.rb",
     "script/surveyor/specs/validation_spec.rb",
     "script/surveyor/survey.rb",
     "script/surveyor/survey_section.rb",
     "script/surveyor/validation.rb",
     "script/surveyor/validation_condition.rb",
     "script/surveyor/whr_dsl.tmproj",
     "spec/controllers/surveyor_controller_spec.rb",
     "spec/factories.rb",
     "spec/lib/surveyor_spec.rb",
     "spec/models/answer_spec.rb",
     "spec/models/dependency_condition_spec.rb",
     "spec/models/dependency_spec.rb",
     "spec/models/question_group_spec.rb",
     "spec/models/question_spec.rb",
     "spec/models/response_set_spec.rb",
     "spec/models/response_spec.rb",
     "spec/models/survey_section_spec.rb",
     "spec/models/survey_spec.rb",
     "spec/models/validation_condition_spec.rb",
     "spec/models/validation_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "surveyor.gemspec",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/breakpointer/surveyor}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A rails (gem) plugin to enable surveys in your application}
  s.test_files = [
    "spec/controllers/surveyor_controller_spec.rb",
     "spec/factories.rb",
     "spec/lib/surveyor_spec.rb",
     "spec/models/answer_spec.rb",
     "spec/models/dependency_condition_spec.rb",
     "spec/models/dependency_spec.rb",
     "spec/models/question_group_spec.rb",
     "spec/models/question_spec.rb",
     "spec/models/response_set_spec.rb",
     "spec/models/response_spec.rb",
     "spec/models/survey_section_spec.rb",
     "spec/models/survey_spec.rb",
     "spec/models/validation_condition_spec.rb",
     "spec/models/validation_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, [">= 0"])
    else
      s.add_dependency(%q<haml>, [">= 0"])
    end
  else
    s.add_dependency(%q<haml>, [">= 0"])
  end
end

