source :rubygems

gem 'rails', '2.3.10'
gem 'rspec', '~> 1.3'
gem 'rspec-rails', '1.3.3'
gem 'sqlite3-ruby', '1.2.5' # Using this version for ruby 1.8.7 compatibility reasons
gem 'webrat'
gem 'cucumber', '~> 0.8.0'
gem 'cucumber-rails'
gem 'database_cleaner'
gem 'factory_girl'
gem 'formtastic'

gem 'surveyor', :path => ".."